args_unknown: '[]'
base_model_name: '"v_48_020"'
batch_size: '10000'
beta: '0.004482823588582285'
debug: None
device: '"cuda"'
domain: '"d"'
env: '"py"'
hyp: None
hyp_n: None
job: '"fwxkh"'
loch_path: None
lr: '4.6198192672191274e-07'
max_protein_length: '10000'
mhc_1_alleles: '"b69bb1"'
mhc_1_predictor: '"pwm_dynamic"'
multithreading: 'False'
num_epochs: '20'
num_examples_per_epoch: '1000000'
project_path: None
reload_data_every_n_epochs: '2'
rescut: '3.5'
save_model_every_n_epochs: '1'
task: '""'
temperature: '0.4990042902656287'
